### YamlMime:ManagedReference
items:
- uid: v3.1.1.0:Xunit.Runners.ErrorMessageType
  commentId: T:Xunit.Runners.ErrorMessageType
  id: ErrorMessageType
  parent: v3.1.1.0:Xunit.Runners
  children:
  - v3.1.1.0:Xunit.Runners.ErrorMessageType.CatastrophicError
  - v3.1.1.0:Xunit.Runners.ErrorMessageType.TestAssemblyCleanupFailure
  - v3.1.1.0:Xunit.Runners.ErrorMessageType.TestCaseCleanupFailure
  - v3.1.1.0:Xunit.Runners.ErrorMessageType.TestClassCleanupFailure
  - v3.1.1.0:Xunit.Runners.ErrorMessageType.TestCleanupFailure
  - v3.1.1.0:Xunit.Runners.ErrorMessageType.TestCollectionCleanupFailure
  - v3.1.1.0:Xunit.Runners.ErrorMessageType.TestMethodCleanupFailure
  langs:
  - csharp
  - vb
  name: ErrorMessageType
  nameWithType: ErrorMessageType
  fullName: Xunit.Runners.ErrorMessageType
  type: Enum
  source:
    remote:
      path: src/xunit.v3.runner.utility/Runners/ErrorMessageType.cs
      branch: 7ad077d8526cb36497a764422ea9b16ed75813d4
      repo: https://github.com/xunit/xunit
    id: ErrorMessageType
    path: ../src/xunit.v3.runner.utility/Runners/ErrorMessageType.cs
    startLine: 5
  assemblies:
  - xunit.v3.runner.utility.netfx
  namespace: Xunit.Runners
  summary: An enumeration which indicates the type of error message (for <xref href="v3.1.1.0:Xunit.Runners.AssemblyRunner.OnErrorMessage" data-throw-if-not-resolved="false"></xref>).
  example: []
  syntax:
    content: public enum ErrorMessageType
    content.vb: Public Enum ErrorMessageType
- uid: v3.1.1.0:Xunit.Runners.ErrorMessageType.CatastrophicError
  commentId: F:Xunit.Runners.ErrorMessageType.CatastrophicError
  id: CatastrophicError
  parent: v3.1.1.0:Xunit.Runners.ErrorMessageType
  langs:
  - csharp
  - vb
  name: CatastrophicError
  nameWithType: ErrorMessageType.CatastrophicError
  fullName: Xunit.Runners.ErrorMessageType.CatastrophicError
  type: Field
  source:
    remote:
      path: src/xunit.v3.runner.utility/Runners/ErrorMessageType.cs
      branch: 7ad077d8526cb36497a764422ea9b16ed75813d4
      repo: https://github.com/xunit/xunit
    id: CatastrophicError
    path: ../src/xunit.v3.runner.utility/Runners/ErrorMessageType.cs
    startLine: 8
  assemblies:
  - xunit.v3.runner.utility.netfx
  namespace: Xunit.Runners
  summary: An unhandled exception occurred that disrupted the execution engine
  example: []
  syntax:
    content: CatastrophicError = 1
    return:
      type: Xunit.Runners.ErrorMessageType
- uid: v3.1.1.0:Xunit.Runners.ErrorMessageType.TestAssemblyCleanupFailure
  commentId: F:Xunit.Runners.ErrorMessageType.TestAssemblyCleanupFailure
  id: TestAssemblyCleanupFailure
  parent: v3.1.1.0:Xunit.Runners.ErrorMessageType
  langs:
  - csharp
  - vb
  name: TestAssemblyCleanupFailure
  nameWithType: ErrorMessageType.TestAssemblyCleanupFailure
  fullName: Xunit.Runners.ErrorMessageType.TestAssemblyCleanupFailure
  type: Field
  source:
    remote:
      path: src/xunit.v3.runner.utility/Runners/ErrorMessageType.cs
      branch: 7ad077d8526cb36497a764422ea9b16ed75813d4
      repo: https://github.com/xunit/xunit
    id: TestAssemblyCleanupFailure
    path: ../src/xunit.v3.runner.utility/Runners/ErrorMessageType.cs
    startLine: 11
  assemblies:
  - xunit.v3.runner.utility.netfx
  namespace: Xunit.Runners
  summary: An unhandled exception happened while cleaning up from the test assembly
  example: []
  syntax:
    content: TestAssemblyCleanupFailure = 10
    return:
      type: Xunit.Runners.ErrorMessageType
- uid: v3.1.1.0:Xunit.Runners.ErrorMessageType.TestCollectionCleanupFailure
  commentId: F:Xunit.Runners.ErrorMessageType.TestCollectionCleanupFailure
  id: TestCollectionCleanupFailure
  parent: v3.1.1.0:Xunit.Runners.ErrorMessageType
  langs:
  - csharp
  - vb
  name: TestCollectionCleanupFailure
  nameWithType: ErrorMessageType.TestCollectionCleanupFailure
  fullName: Xunit.Runners.ErrorMessageType.TestCollectionCleanupFailure
  type: Field
  source:
    remote:
      path: src/xunit.v3.runner.utility/Runners/ErrorMessageType.cs
      branch: 7ad077d8526cb36497a764422ea9b16ed75813d4
      repo: https://github.com/xunit/xunit
    id: TestCollectionCleanupFailure
    path: ../src/xunit.v3.runner.utility/Runners/ErrorMessageType.cs
    startLine: 14
  assemblies:
  - xunit.v3.runner.utility.netfx
  namespace: Xunit.Runners
  summary: An unhandled exception happened while cleaning up from the test collection
  example: []
  syntax:
    content: TestCollectionCleanupFailure = 20
    return:
      type: Xunit.Runners.ErrorMessageType
- uid: v3.1.1.0:Xunit.Runners.ErrorMessageType.TestClassCleanupFailure
  commentId: F:Xunit.Runners.ErrorMessageType.TestClassCleanupFailure
  id: TestClassCleanupFailure
  parent: v3.1.1.0:Xunit.Runners.ErrorMessageType
  langs:
  - csharp
  - vb
  name: TestClassCleanupFailure
  nameWithType: ErrorMessageType.TestClassCleanupFailure
  fullName: Xunit.Runners.ErrorMessageType.TestClassCleanupFailure
  type: Field
  source:
    remote:
      path: src/xunit.v3.runner.utility/Runners/ErrorMessageType.cs
      branch: 7ad077d8526cb36497a764422ea9b16ed75813d4
      repo: https://github.com/xunit/xunit
    id: TestClassCleanupFailure
    path: ../src/xunit.v3.runner.utility/Runners/ErrorMessageType.cs
    startLine: 17
  assemblies:
  - xunit.v3.runner.utility.netfx
  namespace: Xunit.Runners
  summary: An unhandled exception happened while cleaning up from the test class
  example: []
  syntax:
    content: TestClassCleanupFailure = 30
    return:
      type: Xunit.Runners.ErrorMessageType
- uid: v3.1.1.0:Xunit.Runners.ErrorMessageType.TestMethodCleanupFailure
  commentId: F:Xunit.Runners.ErrorMessageType.TestMethodCleanupFailure
  id: TestMethodCleanupFailure
  parent: v3.1.1.0:Xunit.Runners.ErrorMessageType
  langs:
  - csharp
  - vb
  name: TestMethodCleanupFailure
  nameWithType: ErrorMessageType.TestMethodCleanupFailure
  fullName: Xunit.Runners.ErrorMessageType.TestMethodCleanupFailure
  type: Field
  source:
    remote:
      path: src/xunit.v3.runner.utility/Runners/ErrorMessageType.cs
      branch: 7ad077d8526cb36497a764422ea9b16ed75813d4
      repo: https://github.com/xunit/xunit
    id: TestMethodCleanupFailure
    path: ../src/xunit.v3.runner.utility/Runners/ErrorMessageType.cs
    startLine: 20
  assemblies:
  - xunit.v3.runner.utility.netfx
  namespace: Xunit.Runners
  summary: An unhandled exception happened while cleaning up from the test method
  example: []
  syntax:
    content: TestMethodCleanupFailure = 40
    return:
      type: Xunit.Runners.ErrorMessageType
- uid: v3.1.1.0:Xunit.Runners.ErrorMessageType.TestCaseCleanupFailure
  commentId: F:Xunit.Runners.ErrorMessageType.TestCaseCleanupFailure
  id: TestCaseCleanupFailure
  parent: v3.1.1.0:Xunit.Runners.ErrorMessageType
  langs:
  - csharp
  - vb
  name: TestCaseCleanupFailure
  nameWithType: ErrorMessageType.TestCaseCleanupFailure
  fullName: Xunit.Runners.ErrorMessageType.TestCaseCleanupFailure
  type: Field
  source:
    remote:
      path: src/xunit.v3.runner.utility/Runners/ErrorMessageType.cs
      branch: 7ad077d8526cb36497a764422ea9b16ed75813d4
      repo: https://github.com/xunit/xunit
    id: TestCaseCleanupFailure
    path: ../src/xunit.v3.runner.utility/Runners/ErrorMessageType.cs
    startLine: 23
  assemblies:
  - xunit.v3.runner.utility.netfx
  namespace: Xunit.Runners
  summary: An unhandled exception happened while cleaning up from the test case
  example: []
  syntax:
    content: TestCaseCleanupFailure = 50
    return:
      type: Xunit.Runners.ErrorMessageType
- uid: v3.1.1.0:Xunit.Runners.ErrorMessageType.TestCleanupFailure
  commentId: F:Xunit.Runners.ErrorMessageType.TestCleanupFailure
  id: TestCleanupFailure
  parent: v3.1.1.0:Xunit.Runners.ErrorMessageType
  langs:
  - csharp
  - vb
  name: TestCleanupFailure
  nameWithType: ErrorMessageType.TestCleanupFailure
  fullName: Xunit.Runners.ErrorMessageType.TestCleanupFailure
  type: Field
  source:
    remote:
      path: src/xunit.v3.runner.utility/Runners/ErrorMessageType.cs
      branch: 7ad077d8526cb36497a764422ea9b16ed75813d4
      repo: https://github.com/xunit/xunit
    id: TestCleanupFailure
    path: ../src/xunit.v3.runner.utility/Runners/ErrorMessageType.cs
    startLine: 26
  assemblies:
  - xunit.v3.runner.utility.netfx
  namespace: Xunit.Runners
  summary: An unhandled exception happened while cleaning up from the test
  example: []
  syntax:
    content: TestCleanupFailure = 60
    return:
      type: Xunit.Runners.ErrorMessageType
references:
- uid: v3.1.1.0:Xunit.Runners.AssemblyRunner.OnErrorMessage
  commentId: P:Xunit.Runners.AssemblyRunner.OnErrorMessage
  href: Xunit.Runners.AssemblyRunner.OnErrorMessage.html#Xunit_Runners_AssemblyRunner_OnErrorMessage
  name: OnErrorMessage
  nameWithType: AssemblyRunner.OnErrorMessage
  fullName: Xunit.Runners.AssemblyRunner.OnErrorMessage
- uid: v3.1.1.0:Xunit.Runners
  commentId: N:Xunit.Runners
  href: Xunit.html
  name: Xunit.Runners
  nameWithType: Xunit.Runners
  fullName: Xunit.Runners
  spec.csharp:
  - uid: v3.1.1.0:Xunit
    name: Xunit
    href: Xunit.html
  - name: .
  - uid: v3.1.1.0:Xunit.Runners
    name: Runners
    href: Xunit.Runners.html
  spec.vb:
  - uid: v3.1.1.0:Xunit
    name: Xunit
    href: Xunit.html
  - name: .
  - uid: v3.1.1.0:Xunit.Runners
    name: Runners
    href: Xunit.Runners.html
- uid: v3.1.1.0:Xunit.Runners.ErrorMessageType
  commentId: T:Xunit.Runners.ErrorMessageType
  parent: v3.1.1.0:Xunit.Runners
  href: Xunit.Runners.ErrorMessageType.html
  name: ErrorMessageType
  nameWithType: ErrorMessageType
  fullName: Xunit.Runners.ErrorMessageType
memberLayout: SeparatePages
